services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saas_aplicacao
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:${APP_PORT:-8081}
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: saas_mvp
      DB_USERNAME: saas
      DB_PASSWORD: saas
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      SESSION_DRIVER: database
    depends_on:
      - postgres
      - redis
    networks:
      - rede_saas

  nginx:
    image: nginx:1.27-alpine
    container_name: saas_nginx
    ports:
      - "${APP_PORT:-8081}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - rede_saas

  postgres:
    image: postgres:16-alpine
    container_name: saas_postgres
    environment:
      POSTGRES_DB: saas_mvp
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas
    volumes:
      - dados_postgres:/var/lib/postgresql/data
    networks:
      - rede_saas

  redis:
    image: redis:7-alpine
    container_name: saas_redis
    networks:
      - rede_saas

volumes:
  dados_postgres:

networks:
  rede_saas:
    driver: bridge
